version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2015
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps: >-
    dotnet restore

    $buildVersion = "beta1-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"
    
    Dir src/VersionManagement*,test/VersionManagement* -Directory | % { dotnet build --version-suffix $buildVersion $_ }

test_script:
- ps: >-
    Dir test/VersionManagement* -Directory | % { dotnet test $_ }

deploy_script:
- ps: >-
    $buildVersion = "beta1-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"
    Dir src/VersionManagement* -Directory | % { dotnet pack --version-suffix $buildVersion $_ }

artifacts:
- path: src\artifacts\packages\Debug\*.nupkg
