version: 1.0.{build}
branches:
  only:
  - development/r1.0
  - release/r1.0
image: Visual Studio 2015
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- ps: >-
    dotnet restore

    $buildVersion = "beta1-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"
    
    dotnet build --version-suffix $buildVersion "src/VersionManagement*" "test/VersionManagement*"

test_script:
- ps: >-
    Get-Item -Directory test/VersionManagement* | % { dotnet test $_ }

deploy_script:
- ps: >-
    $buildVersion = "beta1-$($env:APPVEYOR_BUILD_NUMBER.PadLeft(4, '0'))"
    Get-Item -Directory src/VersionManagement* | % { dotnet pack --version-suffix $buildVersion $_ }

artifacts:
- path: src\artifacts\packages\Debug\*.nupkg